---
name: Archive
description: create tar.gz archive
on:
  workflow_call:
    inputs:
      base-path:  # base path, will not get included in the archive
        required: false
        default: ${{ github.workspace }}
        type: string
      source-path:  # relative path to be archived
        required: false
        default: .
        type: string
      output-path: # output archive name
        required: false
        default: output.tar.gz
        type: string
runs:
  using: "composite"
  steps:
    - name: create-archive
      run: tar cvzf ${{inputs.output-path}} -C ${{inputs.base-path}} ${{source-path}}
      
      
