---
name: wait-artifact
description: wait and download named artifact
inputs:
  artifact:
    required: true
    description: name of the artifact to wait and optionally download
  download:
    required: false
    default: false
  token:
    required: true
    description: github rest api token
  timeout:
    required: false
    default: 120
runs:
  using: composite
  steps:
    - name: setup
      run: |
        apt update -qq
        apt install -qqy jq curl
      shell: bash
    - name: wait
      run: |
        start="$(date +%s)"
        end="$(( start + ${{inputs.timeout}} ))"
        while true
        do
          current="$(date +%s)"
          if [ $current -gt $end ]
          then
            >&2 echo "exceed timeout"
            exit 1
          fi
          curl -sf -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{inputs.token}}" -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/artifacts" |\
            jq '.' > result.json
          if [ "$(jq -r '.total_count' result.json)" -eq 0 ]
          then
            sleep 10
            continue
          fi
          if [ -z "$(jq --arg artifact "${{ inputs.artifact }}" '.artifacts[] | select( .name == $artifact) ' result.json)" ]
          then
            sleep 10
            continue
          fi
          break
        done
        rm result.json
      shell: bash
    - name: download
      if: ${{ inputs.download }}
      shell: bash
      run: |
        curl -sf \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{inputs.token}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/artifacts" |\
        jq --arg artifact "${{ inputs.artifact }}" '.artifacts[] | select( .name == $artifact) | .archive_download_url' |\
        if read url
        then
          echo "url: $url"
          curl -H "Authorization: Bearer ${{inputs.token}}" -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" -svL $url -o artifacts.zip
          unzip artifacts.zip
          rm artifacts.zip
        else
          exit 1
        fi
