---
name: wait-artifact
description: wait and download named artifact
inputs:
  name:
    required: true
    description: name of the artifact to wait and optionally download
  download:
    required: false
    default: false
  token:
    required: true
    description: github rest api token

runs:
  using: composite
  steps:
    - name: setup
      run: |
        apt update -q
        apt install -qy jq curl
        env
      shell: bash
    - name: wait
      run: |
        while true
        do
          curl -sfv -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{inputs.token}}" -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/artifacts" |\
            jq --arg "${{inputs.name}}" '.' > result.json
          if [ "$(jq '.total_count')" -eq 0 ]
          then
            sleep 10
            continue
          fi
          if [ -z "$(jq --args name "${{inputs.name}}" '.artifacts | select( .name == $name) ')" ]
          then
            sleep 10
            continue
          fi
          break
        done
        rm result.json
      shell: bash
