---
name: wait-artifact
description: wait and download named artifact
inputs:
  name:
    required: true
    description: name of the artifact to wait and optionally download
  download:
    required: false
    default: false
  token:
    required: true
    description: github rest api token

runs:
  using: composite
  steps:
    - name: setup
      run: |
        apt update -q
        apt install -qy jq curl
        env
      shell: bash
    - name: wait
      run: |
        exit 1
        while true
        do
          curl -sf -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{inputs.token}}" -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/${GITHUB_REPOSITORY_OWNER}/${GITHUB_RUN_ID}/actions/runs/${GITHUB_RUN_ID}/artifacts" |\
            jq --arg "${{inputs.name}}" '.'
          # if []
          break
          sleep 10
        done
