---
name: cleanup artifacts
description: delete all artifacts from the build
inputs:
  token: 
    required: false
    default: ${{ github.token }}
    description: github rest api token
runs:
  using: composite
  steps:
    - name: setup
      run: |
        sudo apt update -qq
        sudo apt install -qqy jq curl
      shell: bash
    - name: get artifacts list
      shell: bash
      run: |
        curl -sf -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{inputs.token}}" -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/artifacts" |\
          jq -r '.artifacts[].id' > list.txt
    - name: delete artifacts 
      shell: bash
      run: |
        while read id
        do
          >&2 echo "deleting ${id} https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/artifacts/${id}"
          curl -sv -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{inputs.token}}" -H "X-GitHub-Api-Version: 2022-11-28" \
            -X DELETE "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/artifacts/${id}"
        done < list.txt